### ISSUE TITLE
IntegrityError: null value in column "Occupied seats" violates not-null constraint

### ISSUE THREAD

**Issue by moyamo** [j5int/uct-maths-competition#58]
In Django `blank=True` is validation related and means that an entry is allowed to be left blank in the forms and `null=True` is database related meaning that the value can be null in the database. The "Occupied seats" field has `null=False` and `blank=True` which means the user can leave the entry blank in a form, submit and cause an `IntegrityError` since the database won't allow the value to be `null`.

https://github.com/j5int/uct-maths-competition/blob/6fda5ce7a4f9dd0b3d120118e54eb6f1307497a5/uctMaths/competition/models.py#L89

This can be fixed either by setting `blank=False` or `null=True`. But I'm not sure which one is appropriate in this case.

**Comment by ianwj5int** [comment]
When the venue is created, occupied seats will not be set. It only gets set when entrants are allocated to venues. So I think blank=True and null=True makes more sense.
There might be places where the code assumes non-null, which would have to be updated to treat null as 0.
